### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by nyckmaia** [hapoo/blaze-hdf5#1]
I would like to know if is already possible to work with Blaze and HDF5.

Is this working?

If yes, in which platforms? Windows, Linux and Mac OSX?

Thank you,

**Comment by akheir** [comment]
This was written for a test. It used to work two years ago, but I didn't check it recently to test it with recent changes on blaze or HDF5. I used it on Linux. It has cmake config so it could be configured for any of those platforms.

Feel free to reuse the code.
